openapi: 3.0.3
info:
  title: LinkFlow AI - Workflow Service API
  description: Workflow management service for LinkFlow AI platform
  version: 1.0.0
  contact:
    name: LinkFlow AI Team
    email: api@linkflow.ai
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8004
    description: Development server
  - url: https://api.linkflow.ai
    description: Production server

tags:
  - name: Workflows
    description: Workflow CRUD operations
  - name: Nodes
    description: Workflow node management
  - name: Connections
    description: Node connection management
  - name: Execution
    description: Workflow execution operations

paths:
  /api/v1/workflows:
    get:
      tags:
        - Workflows
      summary: List workflows
      operationId: listWorkflows
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/WorkflowStatus'
        - name: tags
          in: query
          schema:
            type: array
            items:
              type: string
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [name, created_at, updated_at]
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: List of workflows
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowList'
        '401':
          $ref: '#/components/responses/Unauthorized'
    
    post:
      tags:
        - Workflows
      summary: Create workflow
      operationId: createWorkflow
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkflowRequest'
      responses:
        '201':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/workflows/{id}:
    get:
      tags:
        - Workflows
      summary: Get workflow by ID
      operationId: getWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      responses:
        '200':
          description: Workflow details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    
    put:
      tags:
        - Workflows
      summary: Update workflow
      operationId: updateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkflowRequest'
      responses:
        '200':
          description: Workflow updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    
    delete:
      tags:
        - Workflows
      summary: Delete workflow
      operationId: deleteWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      responses:
        '204':
          description: Workflow deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/activate:
    post:
      tags:
        - Workflows
      summary: Activate workflow
      operationId: activateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      responses:
        '200':
          description: Workflow activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/deactivate:
    post:
      tags:
        - Workflows
      summary: Deactivate workflow
      operationId: deactivateWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      responses:
        '200':
          description: Workflow deactivated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/archive:
    post:
      tags:
        - Workflows
      summary: Archive workflow
      operationId: archiveWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      responses:
        '200':
          description: Workflow archived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/clone:
    post:
      tags:
        - Workflows
      summary: Clone workflow
      operationId: cloneWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name for cloned workflow
      responses:
        '201':
          description: Workflow cloned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/execute:
    post:
      tags:
        - Execution
      summary: Execute workflow
      operationId: executeWorkflow
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteWorkflowRequest'
      responses:
        '200':
          description: Execution result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/versions:
    get:
      tags:
        - Workflows
      summary: List workflow versions
      operationId: listWorkflowVersions
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        '200':
          description: Workflow versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowVersionList'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/nodes:
    post:
      tags:
        - Nodes
      summary: Add node to workflow
      operationId: addNode
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
      responses:
        '200':
          description: Node added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/workflows/{id}/nodes/{nodeId}:
    put:
      tags:
        - Nodes
      summary: Update node
      operationId: updateNode
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
      responses:
        '200':
          description: Node updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    
    delete:
      tags:
        - Nodes
      summary: Remove node
      operationId: removeNode
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/WorkflowIdParam'
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Node removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Workflow:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        organizationId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/WorkflowStatus'
        version:
          type: integer
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        settings:
          $ref: '#/components/schemas/WorkflowSettings'
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WorkflowStatus:
      type: string
      enum: [draft, active, inactive, archived]

    Node:
      type: object
      required:
        - id
        - type
        - name
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/NodeType'
        name:
          type: string
        description:
          type: string
        config:
          type: object
        position:
          $ref: '#/components/schemas/Position'

    NodeType:
      type: string
      enum: [trigger, action, condition, loop, transform, output, delay]

    Position:
      type: object
      properties:
        x:
          type: number
        y:
          type: number

    Connection:
      type: object
      required:
        - id
        - sourceNodeId
        - targetNodeId
      properties:
        id:
          type: string
        sourceNodeId:
          type: string
        targetNodeId:
          type: string
        sourcePort:
          type: string
        targetPort:
          type: string

    WorkflowSettings:
      type: object
      properties:
        maxExecutionTime:
          type: integer
          description: Maximum execution time in seconds
        retryPolicy:
          $ref: '#/components/schemas/RetryPolicy'
        errorHandling:
          type: string
          enum: [stop, continue, retry]
        metadata:
          type: object

    RetryPolicy:
      type: object
      properties:
        maxAttempts:
          type: integer
        backoffType:
          type: string
          enum: [linear, exponential, constant]
        delaySeconds:
          type: integer

    WorkflowList:
      type: object
      properties:
        workflows:
          type: array
          items:
            $ref: '#/components/schemas/Workflow'
        totalCount:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer

    WorkflowVersionList:
      type: object
      properties:
        versions:
          type: array
          items:
            type: object
            properties:
              version:
                type: integer
              createdAt:
                type: string
                format: date-time
              changes:
                type: string
        totalCount:
          type: integer

    CreateWorkflowRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        settings:
          $ref: '#/components/schemas/WorkflowSettings'
        tags:
          type: array
          items:
            type: string

    UpdateWorkflowRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        settings:
          $ref: '#/components/schemas/WorkflowSettings'
        tags:
          type: array
          items:
            type: string

    ExecuteWorkflowRequest:
      type: object
      properties:
        input:
          type: object
        context:
          type: object
        async:
          type: boolean
          default: false

    ExecutionResult:
      type: object
      properties:
        executionId:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, running, completed, failed, cancelled]
        output:
          type: object
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionError'
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time

    ExecutionError:
      type: object
      properties:
        nodeId:
          type: string
        code:
          type: string
        message:
          type: string
        details:
          type: object

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  parameters:
    WorkflowIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Workflow ID

    PageParam:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number

    PageSizeParam:
      name: pageSize
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: Items per page

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
